### PR TITLE
Rewrite existing Workspace docs, make compatible with dumpling

### PR DESCRIPTION
**Pull request by jovannic**
Updated the front matter to use the toml front matter format used by dumpling.

Combined workspace files.

Rewrote contents of the one file that had any documentation. Attempted to add more details and distinguish it from just being a copy of the devhub docs. We should be able to do better.

PR instead of submitting directly because I'm unsure how we actually want to structure these files longer term. Dumpling at least doesn't enforce any kind of file structure. Soft preference for keeping docs for the same class in the same file but could go either way.

### CODE REVIEW

**Comment by bradsharp** [comment]
So @LPGhatguy and I have been discussing the format. Might be worth setting up a channel so we can keep everyone in the loop.

Agree we can write our own documentation, this was just copied for the sake of having a file to test with. We should definitely migrate the documentation from dumpling over.

I'll let @LPGhatguy jump in if I'm wrong. I believe the plan is to have a folder for each instance. The folder will contain \<className\>.md along with a unique file for each member. Managing classes such as `Humanoid` and `Workspace` in a single-file is something I'd like to avoid given the sheer number of members they have. I also think this would align better with page boundaries, assuming we were to have a page for each member in the future.

As for the format of each file, I've been discussing YAML with @LPGhatguy as it renders nicely in GitHub's markdown previewer, though this is obviously not a huge deal. The format of the front-matter is really a question of if we do split each member into a unique file, what attributes would we want to store in that file?

**Comment by jovannic** [comment]
I'd have a preference for having a single page per class in a wiki myself. Java, AS3, and Rust docs all put the docs for members on a single page. Nicer for jumping around and getting a better feel for the class as a whole. Yeah the page is long, but I don't think that's a problem at all. Similar soft preference on the files. "big" files don't scare me.

Of course wiki page structure is a separate debate from the file structure though.

**Comment by LPGhatguy** [comment]
Whether we use a folder per instance or break them into multiple files doesn't matter, since we intentionally have an explicit `target` attribute to enable whatever we want.

As far as TOML vs YAML, I've got preference for TOML because it's much better specified, isn't a superset of another (also complicated) format, and doesn't have significant whitespace. If our Markdown files have indentation, they would have to be indented with 2 or 4 spaces if our front-matter is YAML.

**Review by bradsharp — COMMENTED** [review]
Unsure about capitalization here, the dump capitilizes fields, so for consistency it might make sense if we pull out attributes in the same way.

**Review by bradsharp — COMMENTED** [review]
Purpose of descriptions is for the big non-wiki wiki. It's essentially a snippet that we can display if we need to.

**Review by LPGhatguy — APPROVED** [review]

**Pull request merged**
